"""add_currency_and_amount_usd_to_transactions

Revision ID: 4ce4d93bacc9
Revises: 6653f68cdc72
Create Date: 2026-04-02 03:34:54.727907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce4d93bacc9'
down_revision: Union[str, None] = '6653f68cdc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'))
        batch_op.add_column(sa.Column('amount_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('amount_usd')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
