"""initial_schema_v1

Revision ID: 6653f68cdc72
Revises: 
Create Date: 2026-04-01 17:45:41.220504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6653f68cdc72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_account_id', 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_transactions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_column('account_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('merchant')

    # ### end Alembic commands ###
