#!/usr/bin/env bash
# daily-briefing.sh — Vault project status briefing
# Run this script each morning (or ask the Command agent to run it).
# Output is a formatted markdown briefing ready to paste into Paperclip.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/apps/backend"
TODAY=$(date '+%Y-%m-%d')
YESTERDAY=$(date -v-1d '+%Y-%m-%d' 2>/dev/null || date -d 'yesterday' '+%Y-%m-%d')

echo "# Vault Daily Briefing — $TODAY"
echo ""

# ── GIT STATUS ──────────────────────────────────────────────────────────────
echo "## Git"
echo ""

cd "$REPO_ROOT"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "**Branch:** \`$BRANCH\`"

LAST_COMMIT=$(git log -1 --format="%h — %s (%ar)" 2>/dev/null || echo "no commits")
echo "**Last commit:** $LAST_COMMIT"

COMMITS_TODAY=$(git log --oneline --since="$YESTERDAY 23:59" 2>/dev/null | wc -l | tr -d ' ')
echo "**Commits since yesterday:** $COMMITS_TODAY"

UNCOMMITTED=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
if [ "$UNCOMMITTED" -gt 0 ]; then
  echo "**Uncommitted changes:** $UNCOMMITTED files (run \`git status\` to see)"
else
  echo "**Uncommitted changes:** none"
fi

echo ""

# ── BACKEND HEALTH ───────────────────────────────────────────────────────────
echo "## Backend (FastAPI :8000)"
echo ""

HEALTH=$(curl -s --max-time 3 http://localhost:8000/api/health 2>/dev/null || echo "OFFLINE")
if echo "$HEALTH" | grep -q '"ok"'; then
  echo "**Status:** running"
else
  echo "**Status:** OFFLINE — start with \`cd apps/backend && source .venv/bin/activate && python main.py\`"
fi

# ── DATABASE ─────────────────────────────────────────────────────────────────
echo ""
echo "## Database"
echo ""

DB="$BACKEND_DIR/vault.db"
if [ -f "$DB" ]; then
  TX_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM transactions;" 2>/dev/null || echo "?")
  TX_TODAY=$(sqlite3 "$DB" "SELECT COUNT(*) FROM transactions WHERE date >= '$TODAY';" 2>/dev/null || echo "?")
  INCOME=$(sqlite3 "$DB" "SELECT ROUND(SUM(amount),2) FROM transactions WHERE type='income';" 2>/dev/null || echo "?")
  EXPENSES=$(sqlite3 "$DB" "SELECT ROUND(SUM(amount),2) FROM transactions WHERE type='expense';" 2>/dev/null || echo "?")
  echo "**Total transactions:** $TX_COUNT  |  **Added today:** $TX_TODAY"
  echo "**All-time income:** \$$INCOME  |  **All-time expenses:** \$$EXPENSES"
else
  echo "**vault.db not found** — will be created when backend starts"
fi

# ── CODE HEALTH ───────────────────────────────────────────────────────────────
echo ""
echo "## Code Health"
echo ""

cd "$REPO_ROOT"

TODO_COUNT=$(grep -r "TODO\|FIXME\|HACK\|XXX" \
  --include="*.ts" --include="*.tsx" --include="*.py" \
  --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=.git \
  . 2>/dev/null || true | wc -l | tr -d ' ')
echo "**TODO/FIXME markers:** $TODO_COUNT"

PY_FILES=$(find apps/backend -name "*.py" -not -path '*/.venv/*' -not -path '*/__pycache__/*' 2>/dev/null | wc -l | tr -d ' ')
TS_FILES=$(find apps/web/src -name "*.ts" -o -name "*.tsx" 2>/dev/null | wc -l | tr -d ' ')
echo "**Python files:** $PY_FILES  |  **TS/TSX files:** $TS_FILES"

# ── RECENT COMMITS LOG ────────────────────────────────────────────────────────
echo ""
echo "## Recent Commits (last 5)"
echo ""
echo '```'
git log --oneline -5 2>/dev/null || echo "no commits"
echo '```'

# ── ROADMAP SNAPSHOT ─────────────────────────────────────────────────────────
echo ""
echo "## Roadmap Snapshot"
echo ""
echo "| # | Feature | Status |"
echo "|---|---------|--------|"
echo "| 1 | User authentication (JWT) | pending |"
echo "| 2 | Alembic migrations | pending |"
echo "| 3 | Multi-currency support | pending |"
echo "| 4 | Stock market data integration | pending |"
echo "| 5 | Crypto tracking | pending |"
echo "| 6 | Inflation tools (Latin America) | pending |"
echo "| 7 | Mobile feature parity (Expo) | pending |"

echo ""
echo "---"
echo "*Generated by \`scripts/daily-briefing.sh\` on $TODAY*"
